# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 1000 # Timeout for commands executed by starship (in milliseconds).

[nodejs]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[λ](bold yellow)'
