return function()
  -- require("toggleterm").setup {
  --   -- size = 20,
  --   -- open_mapping = [[<C-\>]],
  --   -- -- close_on_exit = true,
  --   -- -- hide_numbers = true,
  --   -- -- shade_filetypes = {},
  --   -- -- shade_terminals = true,
  --   -- -- shading_factor = 2,
  --   -- -- start_in_insert = true,
  --   -- -- insert_mappings = true,
  --   -- -- persist_size = true,
  --   -- -- terminal_mappings = true,
  --   -- -- shell = vim.o.shell,
  --   -- -- direction = 'horizontal', -- vertical' | 'horizontal' | 'window' | 'float',
  --   -- -- highlights = {
  --   -- --   -- highlights which map to a highlight group name and a table of it's values
  --   -- --   -- NOTE: this is only a subset of values, any group placed here will be set for the terminal window split
  --   -- --   Normal = {
  --   -- --     guibg = <VALUE-HERE>,
  --   -- --   },
  --   -- --   NormalFloat = {
  --   -- --     link = 'Normal'
  --   -- --   },
  --   -- --   FloatBorder = {
  --   -- --     guifg = <VALUE-HERE>,
  --   -- --     guibg = <VALUE-HERE>,
  --   -- --   },
  --   -- -- },
  --   -- -- float_opts = {
  --   -- --   border = 'curved',
  --   -- --   winblend = 3,
  --   -- -- }
  -- }
  --
  -- -- function _G.set_terminal_keymaps()
  -- --   local opts = {noremap = true}
  -- --   vim.api.nvim_buf_set_keymap(0, 't', '<esc>', [[<C-\><C-n>]], opts)
  -- --   vim.api.nvim_buf_set_keymap(0, 't', 'jk', [[<C-\><C-n>]], opts)
  -- --   vim.api.nvim_buf_set_keymap(0, 't', '<C-h>', [[<C-\><C-n><C-W>h]], opts)
  -- --   vim.api.nvim_buf_set_keymap(0, 't', '<C-j>', [[<C-\><C-n><C-W>j]], opts)
  -- --   vim.api.nvim_buf_set_keymap(0, 't', '<C-k>', [[<C-\><C-n><C-W>k]], opts)
  -- --   vim.api.nvim_buf_set_keymap(0, 't', '<C-l>', [[<C-\><C-n><C-W>l]], opts)
  -- -- end
  -- --
  -- -- -- if you only want these mappings for toggle term use term://*toggleterm#* instead
  -- -- vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
end
